# 服务端口
server.port=8080

# 数据库连接配置 (注意端口是 3307)
spring.datasource.url=jdbc:mysql://localhost:3307/task_manager?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis 配置 (开启驼峰命名转换，比如数据库的 assignee_id 会自动映射到 Java的 assigneeId)
mybatis.configuration.map-underscore-to-camel-case=true